name: Feature request
description: Suggest an improvement or new module
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Feature ideas are welcome. Please keep the script safe and opt-in.
  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed change
      description: Include the command(s) you want to run and any new flags/modules.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false

